/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpv;

import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import net.sf.jasperreports.swing.JRViewer;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Josito
 */
public class Pantalla_Seleccion_Fecha_Informe extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Seleccion_Fecha_Informe
     */
    button btn = new button();

    public Pantalla_Seleccion_Fecha_Informe() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.generarBotones();
    }

    private void generarBotones() {
        //Creamos un modelo para el JDatePanel
        UtilDateModel model = new UtilDateModel();
        model.setDate(2021, 0, 1);
        model.setSelected(true);
        
        UtilDateModel model2 = new UtilDateModel();
        model2.setDate(2021, 0, 1);
        model2.setSelected(true);

        //Creamos unas propiedades para el JDatePanel
        Properties p1 = new Properties();
        p1.put("text.today", "Today");
        p1.put("text.month", "Month");
        p1.put("text.year", "Year");
        JDatePanelImpl datePanel1 = new JDatePanelImpl(model, p1);
        
        //Creamos unas propiedades para el JDatePanel
        Properties p2 = new Properties();
        p2.put("text.today", "Today");
        p2.put("text.month", "Month");
        p2.put("text.year", "Year");
        JDatePanelImpl datePanel2 = new JDatePanelImpl(model2, p2);

        //Cremos el JDatePicker con ese JDatePanel y con el formate que tenemos en la clase DateLabelFormatter
        JDatePickerImpl datePicker1 = new JDatePickerImpl(datePanel1, new DateLabelFormatter());
        panel.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 30, 180, 30));
        
        JDatePickerImpl datePicker2 = new JDatePickerImpl(datePanel2, new DateLabelFormatter());
        panel.add(datePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 180, 30));
        
        JButton volver = btn.creaButton(null, "ATRAS", 19);
        panel.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 80));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });

        JButton generar = btn.creaButton(null, "GENERAR", 19);
        panel.add(generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 117, 160, 80));
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Informes informe = new Informes();
                    JRViewer informeV = informe.crearInformeVentas(datePicker1.getJFormattedTextField().getText(),datePicker2.getJFormattedTextField().getText());
                    PantallaInforme pi = new PantallaInforme(informeV);
                    pi.setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Pantalla_Seleccion_Fecha_Informe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(30, 30, 30));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha Inicio Venta");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ultima Fecha Venta");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 65, -1, -1));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Seleccion_Fecha_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Seleccion_Fecha_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Seleccion_Fecha_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Seleccion_Fecha_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Seleccion_Fecha_Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
